In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

4 row, 5 col

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
ranarr = np.random.randint(0,50,10)

In [8]:
ranarr.max()

47

In [9]:
import pandas as pd

In [10]:
ser = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [11]:
ser.isnull()

USA        False
Germany    False
USSR       False
Japan      False
dtype: bool

確認是否有空值

In [12]:
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [13]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean  -0.385376  0.019885  0.124774 -0.015462
std    0.392885  0.845531  0.671676  0.795083
min   -0.843088 -0.786354 -0.962606 -1.339986
25%   -0.678930 -0.690545  0.094735 -0.084437
50%   -0.425132 -0.056780  0.127587  0.239378
75%   -0.050382  0.353015  0.674512  0.386109
max    0.070650  1.280087  0.689642  0.721628

敘述統計

In [14]:
df.sort_values(by='X') 

W         X         Y         Z
D -0.843088 -0.786354  0.689642 -1.339986
C -0.678930 -0.690545  0.094735 -0.084437
A  0.070650 -0.056780 -0.962606  0.386109
B -0.425132  0.353015  0.674512  0.721628
E -0.050382  1.280087  0.127587  0.239378

依x 排序

In [15]:
df.drop('new',axis=1)

KeyError: "['new'] not found in axis"

In [ ]:
df.rename(index={'A':'CA', 'B':'NY', 'C':'WY', 'D':'OR', 'E':'CO'}, inplace=True)

重新取名

In [ ]:
df['V'] = [1, 2, np.nan, np.nan, 5]

In [ ]:
df.isnull().sum()

遺失值加總

In [ ]:
df.isnull().sum().sum()

### Exercise

In [22]:
list1 = [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]]
columns = ['Math', 'English', 'History']
index=['Simon','Allen','Jimmy','Peter']

In [59]:
df = pd.DataFrame(list1,index=index,columns=columns)
df

Math  English  History
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60

2.

In [24]:
 df[(df['Math']>65)&(df['English']>85)]

Math  English  History
Jimmy    70       90       88

#計算各科的平均數

In [25]:
df.mean()

Math       72.5
English    67.5
History    64.0
dtype: float64

依各科分數來個別排名

In [26]:
df.rank() 

Math  English  History
Simon   4.0      2.0      1.0
Allen   1.0      3.0      3.0
Jimmy   2.0      4.0      4.0
Peter   3.0      1.0      2.0

新增性別資料

In [27]:
df['Gender']= ['M','F','M','M']

性別的類別各出現幾次？

In [53]:
sum(df['Gender']=='M')


3

In [54]:
sum(df['Gender']=='F')

1

算出每位同學的平均分數，再用平均分數排名

In [70]:
df['mean']=df.mean(axis=1)
df.sort_values(by='mean')

Math  English  History     mean
Simon    90       60       33  69.9375
Peter    80       50       60  72.1250
Allen    50       70       75  73.6875
Jimmy    70       90       88  90.2500